[connections.snowflake]
account = "le64521.west-europe.azure"
user = "danrichfield"
password = "ZXjcKHeW4MLsU65"
role = "ACCOUNTADMIN"
warehouse = "PC_FIVETRAN_WH"
database = "PC_FIVETRAN_DB"
schema = "DBT_FIVETRAN_NETSUITE"
client_session_keep_alive = true